### ISSUE TITLE
Running in browser env, path and fs packages are not resolved

### ISSUE THREAD

**Issue by xzilja** [pinqy520/yoga-layout-wasm#2]
I believe this will only be an issue with bundlers that don't polyfil node packages for browsers, I am using webpack 5 for this (webpack 4 polyfils them).

Essentially getting errors coming from `node_modules/yoga-layout-wasm/dist`

```zsh
Module not found: Error: Can't resolve 'fs'
Module not found: Error: Can't resolve 'path'
```

**Comment by pinqy520** [comment]
Thanks for the correction, I updated how to configure in the document~
